exports.CITIES = [
  { value: '', label: 'Abilene' },
  { value: '', label: 'Addison' },
  { value: '', label: 'Akron' },
  { value: '', label: 'Alameda' },
  { value: '', label: 'Albany' },
  { value: '', label: 'Albany' },
  { value: '', label: 'Albany' },
  { value: '', label: 'Albuquerque' },
  { value: '', label: 'Alexandria' },
  { value: '', label: 'Alexandria' },
  { value: '', label: 'Alhambra' },
  { value: '', label: 'Aliso Viejo' },
  { value: '', label: 'Allen' },
  { value: '', label: 'Allentown' },
  { value: '', label: 'Alpharetta' },
  { value: '', label: 'Altamonte Springs' },
  { value: '', label: 'Altoona' },
  { value: '', label: 'Amarillo' },
  { value: '', label: 'Ames' },
  { value: '', label: 'Anaheim' },
  { value: '', label: 'Anchorage' },
  { value: '', label: 'Anderson' },
  { value: '', label: 'Ankeny' },
  { value: '', label: 'Ann Arbor' },
  { value: '', label: 'Annapolis' },
  { value: '', label: 'Antioch' },
  { value: '', label: 'Apache Junction' },
  { value: '', label: 'Apex' },
  { value: '', label: 'Apopka' },
  { value: '', label: 'Apple Valley' },
  { value: '', label: 'Apple Valley' },
  { value: '', label: 'Appleton' },
  { value: '', label: 'Arcadia' },
  { value: '', label: 'Arlington' },
  { value: '', label: 'Arlington Heights' },
  { value: '', label: 'Arvada' },
  { value: '', label: 'Asheville' },
  { value: '', label: 'Athens-Clarke County' },
  { value: '', label: 'Atlanta' },
  { value: '', label: 'Atlantic City' },
  { value: '', label: 'Attleboro' },
  { value: '', label: 'Auburn' },
  { value: '', label: 'Auburn' },
  { value: '', label: 'Augusta-Richmond County' },
  { value: '', label: 'Aurora' },
  { value: '', label: 'Aurora' },
  { value: '', label: 'Austin' },
  { value: '', label: 'Aventura' },
  { value: '', label: 'Avondale' },
  { value: '', label: 'Azusa' },
  { value: '', label: 'Bakersfield' },
  { value: '', label: 'Baldwin Park' },
  { value: '', label: 'Baltimore' },
  { value: '', label: 'Barnstable Town' },
  { value: '', label: 'Bartlett' },
  { value: '', label: 'Bartlett' },
  { value: '', label: 'Baton Rouge' },
  { value: '', label: 'Battle Creek' },
  { value: '', label: 'Bayonne' },
  { value: '', label: 'Baytown' },
  { value: '', label: 'Beaumont' },
  { value: '', label: 'Beaumont' },
  { value: '', label: 'Beavercreek' },
  { value: '', label: 'Beaverton' },
  { value: '', label: 'Bedford' },
  { value: '', label: 'Bell Gardens' },
  { value: '', label: 'Belleville' },
  { value: '', label: 'Bellevue' },
  { value: '', label: 'Bellevue' },
  { value: '', label: 'Bellflower' },
  { value: '', label: 'Bellingham' },
  { value: '', label: 'Beloit' },
  { value: '', label: 'Bend' },
  { value: '', label: 'Bentonville' },
  { value: '', label: 'Berkeley' },
  { value: '', label: 'Berwyn' },
  { value: '', label: 'Bethlehem' },
  { value: '', label: 'Beverly' },
  { value: '', label: 'Billings' },
  { value: '', label: 'Biloxi' },
  { value: '', label: 'Binghamton' },
  { value: '', label: 'Birmingham' },
  { value: '', label: 'Bismarck' },
  { value: '', label: 'Blacksburg' },
  { value: '', label: 'Blaine' },
  { value: '', label: 'Bloomington' },
  { value: '', label: 'Bloomington' },
  { value: '', label: 'Bloomington' },
  { value: '', label: 'Blue Springs' },
  { value: '', label: 'Boca Raton' },
  { value: '', label: 'Boise City' },
  { value: '', label: 'Bolingbrook' },
  { value: '', label: 'Bonita Springs' },
  { value: '', label: 'Bossier City' },
  { value: '', label: 'Boston' },
  { value: '', label: 'Boulder' },
  { value: '', label: 'Bountiful' },
  { value: '', label: 'Bowie' },
  { value: '', label: 'Bowling Green' },
  { value: '', label: 'Boynton Beach' },
  { value: '', label: 'Bozeman' },
  { value: '', label: 'Bradenton' },
  { value: '', label: 'Brea' },
  { value: '', label: 'Bremerton' },
  { value: '', label: 'Brentwood' },
  { value: '', label: 'Brentwood' },
  { value: '', label: 'Bridgeport' },
  { value: '', label: 'Bristol' },
  { value: '', label: 'Brockton' },
  { value: '', label: 'Broken Arrow' },
  { value: '', label: 'Brookfield' },
  { value: '', label: 'Brookhaven' },
  { value: '', label: 'Brooklyn Park' },
  { value: '', label: 'Broomfield' },
  { value: '', label: 'Brownsville' },
  { value: '', label: 'Bryan' },
  { value: '', label: 'Buckeye' },
  { value: '', label: 'Buena Park' },
  { value: '', label: 'Buffalo' },
  { value: '', label: 'Buffalo Grove' },
  { value: '', label: 'Bullhead City' },
  { value: '', label: 'Burbank' },
  { value: '', label: 'Burien' },
  { value: '', label: 'Burleson' },
  { value: '', label: 'Burlington' },
  { value: '', label: 'Burlington' },
  { value: '', label: 'Burnsville' },
  { value: '', label: 'Caldwell' },
  { value: '', label: 'Calexico' },
  { value: '', label: 'Calumet City' },
  { value: '', label: 'Camarillo' },
  { value: '', label: 'Cambridge' },
  { value: '', label: 'Camden' },
  { value: '', label: 'Campbell' },
  { value: '', label: 'Canton' },
  { value: '', label: 'Cape Coral' },
  { value: '', label: 'Cape Girardeau' },
  { value: '', label: 'Carlsbad' },
  { value: '', label: 'Carmel' },
  { value: '', label: 'Carol Stream' },
  { value: '', label: 'Carpentersville' },
  { value: '', label: 'Carrollton' },
  { value: '', label: 'Carson' },
  { value: '', label: 'Carson City' },
  { value: '', label: 'Cary' },
  { value: '', label: 'Casa Grande' },
  { value: '', label: 'Casper' },
  { value: '', label: 'Castle Rock' },
  { value: '', label: 'Cathedral City' },
  { value: '', label: 'Cedar Falls' },
  { value: '', label: 'Cedar Hill' },
  { value: '', label: 'Cedar Park' },
  { value: '', label: 'Cedar Rapids' },
  { value: '', label: 'Centennial' },
  { value: '', label: 'Ceres' },
  { value: '', label: 'Cerritos' },
  { value: '', label: 'Champaign' },
  { value: '', label: 'Chandler' },
  { value: '', label: 'Chapel Hill' },
  { value: '', label: 'Charleston' },
  { value: '', label: 'Charleston' },
  { value: '', label: 'Charlotte' },
  { value: '', label: 'Charlottesville' },
  { value: '', label: 'Chattanooga' },
  { value: '', label: 'Chelsea' },
  { value: '', label: 'Chesapeake' },
  { value: '', label: 'Chesterfield' },
  { value: '', label: 'Cheyenne' },
  { value: '', label: 'Chicago' },
  { value: '', label: 'Chico' },
  { value: '', label: 'Chicopee' },
  { value: '', label: 'Chino' },
  { value: '', label: 'Chino Hills' },
  { value: '', label: 'Chula Vista' },
  { value: '', label: 'Cicero' },
  { value: '', label: 'Cincinnati' },
  { value: '', label: 'Citrus Heights' },
  { value: '', label: 'Clarksville' },
  { value: '', label: 'Clearwater' },
  { value: '', label: 'Cleveland' },
  { value: '', label: 'Cleveland' },
  { value: '', label: 'Cleveland Heights' },
  { value: '', label: 'Clifton' },
  { value: '', label: 'Clovis' },
  { value: '', label: 'Clovis' },
  { value: '', label: 'Coachella' },
  { value: '', label: 'Coconut Creek' },
  { value: '', label: 'Coeur d\'Alene' },
  { value: '', label: 'College Station' },
  { value: '', label: 'Collierville' },
  { value: '', label: 'Colorado Springs' },
  { value: '', label: 'Colton' },
  { value: '', label: 'Columbia' },
  { value: '', label: 'Columbia' },
  { value: '', label: 'Columbus' },
  { value: '', label: 'Columbus' },
  { value: '', label: 'Columbus' },
  { value: '', label: 'Commerce City' },
  { value: '', label: 'Compton' },
  { value: '', label: 'Concord' },
  { value: '', label: 'Concord' },
  { value: '', label: 'Concord' },
  { value: '', label: 'Conroe' },
  { value: '', label: 'Conway' },
  { value: '', label: 'Coon Rapids' },
  { value: '', label: 'Coppell' },
  { value: '', label: 'Coral Gables' },
  { value: '', label: 'Coral Springs' },
  { value: '', label: 'Corona' },
  { value: '', label: 'Corpus Christi' },
  { value: '', label: 'Corvallis' },
  { value: '', label: 'Costa Mesa' },
  { value: '', label: 'Council Bluffs' },
  { value: '', label: 'Covina' },
  { value: '', label: 'Covington' },
  { value: '', label: 'Cranston' },
  { value: '', label: 'Crystal Lake' },
  { value: '', label: 'Culver City' },
  { value: '', label: 'Cupertino' },
  { value: '', label: 'Cutler Bay' },
  { value: '', label: 'Cuyahoga Falls' },
  { value: '', label: 'Cypress' },
  { value: '', label: 'Dallas' },
  { value: '', label: 'Daly City' },
  { value: '', label: 'Danbury' },
  { value: '', label: 'Danville' },
  { value: '', label: 'Danville' },
  { value: '', label: 'Davenport' },
  { value: '', label: 'Davie' },
  { value: '', label: 'Davis' },
  { value: '', label: 'Dayton' },
  { value: '', label: 'Daytona Beach' },
  { value: '', label: 'DeKalb' },
  { value: '', label: 'DeSoto' },
  { value: '', label: 'Dearborn' },
  { value: '', label: 'Dearborn Heights' },
  { value: '', label: 'Decatur' },
  { value: '', label: 'Decatur' },
  { value: '', label: 'Deerfield Beach' },
  { value: '', label: 'Delano' },
  { value: '', label: 'Delray Beach' },
  { value: '', label: 'Deltona' },
  { value: '', label: 'Denton' },
  { value: '', label: 'Denver' },
  { value: '', label: 'Des Moines' },
  { value: '', label: 'Des Plaines' },
  { value: '', label: 'Detroit' },
  { value: '', label: 'Diamond Bar' },
  { value: '', label: 'Doral' },
  { value: '', label: 'Dothan' },
  { value: '', label: 'Dover' },
  { value: '', label: 'Downers Grove' },
  { value: '', label: 'Downey' },
  { value: '', label: 'Draper' },
  { value: '', label: 'Dublin' },
  { value: '', label: 'Dublin' },
  { value: '', label: 'Dubuque' },
  { value: '', label: 'Duluth' },
  { value: '', label: 'Duncanville' },
  { value: '', label: 'Dunwoody' },
  { value: '', label: 'Durham' },
  { value: '', label: 'Eagan' },
  { value: '', label: 'East Lansing' },
  { value: '', label: 'East Orange' },
  { value: '', label: 'East Providence' },
  { value: '', label: 'Eastvale' },
  { value: '', label: 'Eau Claire' },
  { value: '', label: 'Eden Prairie' },
  { value: '', label: 'Edina' },
  { value: '', label: 'Edinburg' },
  { value: '', label: 'Edmond' },
  { value: '', label: 'Edmonds' },
  { value: '', label: 'El Cajon' },
  { value: '', label: 'El Centro' },
  { value: '', label: 'El Monte' },
  { value: '', label: 'El Paso' },
  { value: '', label: 'Elgin' },
  { value: '', label: 'Elizabeth' },
  { value: '', label: 'Elk Grove' },
  { value: '', label: 'Elkhart' },
  { value: '', label: 'Elmhurst' },
  { value: '', label: 'Elyria' },
  { value: '', label: 'Encinitas' },
  { value: '', label: 'Enid' },
  { value: '', label: 'Erie' },
  { value: '', label: 'Escondido' },
  { value: '', label: 'Euclid' },
  { value: '', label: 'Eugene' },
  { value: '', label: 'Euless' },
  { value: '', label: 'Evanston' },
  { value: '', label: 'Evansville' },
  { value: '', label: 'Everett' },
  { value: '', label: 'Everett' },
  { value: '', label: 'Fairfield' },
  { value: '', label: 'Fairfield' },
  { value: '', label: 'Fall River' },
  { value: '', label: 'Fargo' },
  { value: '', label: 'Farmington' },
  { value: '', label: 'Farmington Hills' },
  { value: '', label: 'Fayetteville' },
  { value: '', label: 'Fayetteville' },
  { value: '', label: 'Federal Way' },
  { value: '', label: 'Findlay' },
  { value: '', label: 'Fishers' },
  { value: '', label: 'Fitchburg' },
  { value: '', label: 'Flagstaff' },
  { value: '', label: 'Flint' },
  { value: '', label: 'Florence' },
  { value: '', label: 'Florence' },
  { value: '', label: 'Florissant' },
  { value: '', label: 'Flower Mound' },
  { value: '', label: 'Folsom' },
  { value: '', label: 'Fond du Lac' },
  { value: '', label: 'Fontana' },
  { value: '', label: 'Fort Collins' },
  { value: '', label: 'Fort Lauderdale' },
  { value: '', label: 'Fort Myers' },
  { value: '', label: 'Fort Pierce' },
  { value: '', label: 'Fort Smith' },
  { value: '', label: 'Fort Wayne' },
  { value: '', label: 'Fort Worth' },
  { value: '', label: 'Fountain Valley' },
  { value: '', label: 'Franklin' },
  { value: '', label: 'Frederick' },
  { value: '', label: 'Freeport' },
  { value: '', label: 'Fremont' },
  { value: '', label: 'Fresno' },
  { value: '', label: 'Friendswood' },
  { value: '', label: 'Frisco' },
  { value: '', label: 'Fullerton' },
  { value: '', label: 'Gainesville' },
  { value: '', label: 'Gaithersburg' },
  { value: '', label: 'Galveston' },
  { value: '', label: 'Garden Grove' },
  { value: '', label: 'Gardena' },
  { value: '', label: 'Garland' },
  { value: '', label: 'Gary' },
  { value: '', label: 'Gastonia' },
  { value: '', label: 'Georgetown' },
  { value: '', label: 'Germantown' },
  { value: '', label: 'Gilbert' },
  { value: '', label: 'Gilroy' },
  { value: '', label: 'Glendale' },
  { value: '', label: 'Glendale' },
  { value: '', label: 'Glendora' },
  { value: '', label: 'Glenview' },
  { value: '', label: 'Goodyear' },
  { value: '', label: 'Goose Creek' },
  { value: '', label: 'Grand Forks' },
  { value: '', label: 'Grand Island' },
  { value: '', label: 'Grand Junction' },
  { value: '', label: 'Grand Prairie' },
  { value: '', label: 'Grand Rapids' },
  { value: '', label: 'Grapevine' },
  { value: '', label: 'Great Falls' },
  { value: '', label: 'Greeley' },
  { value: '', label: 'Green Bay' },
  { value: '', label: 'Greenacres' },
  { value: '', label: 'Greenfield' },
  { value: '', label: 'Greensboro' },
  { value: '', label: 'Greenville' },
  { value: '', label: 'Greenville' },
  { value: '', label: 'Greenwood' },
  { value: '', label: 'Gresham' },
  { value: '', label: 'Grove City' },
  { value: '', label: 'Gulfport' },
  { value: '', label: 'Hackensack' },
  { value: '', label: 'Hagerstown' },
  { value: '', label: 'Hallandale Beach' },
  { value: '', label: 'Haltom City' },
  { value: '', label: 'Hamilton' },
  { value: '', label: 'Hammond' },
  { value: '', label: 'Hampton' },
  { value: '', label: 'Hanford' },
  { value: '', label: 'Hanover Park' },
  { value: '', label: 'Harlingen' },
  { value: '', label: 'Harrisburg' },
  { value: '', label: 'Harrisonburg' },
  { value: '', label: 'Hartford' },
  { value: '', label: 'Hattiesburg' },
  { value: '', label: 'Haverhill' },
  { value: '', label: 'Hawthorne' },
  { value: '', label: 'Hayward' },
  { value: '', label: 'Hemet' },
  { value: '', label: 'Hempstead' },
  { value: '', label: 'Henderson' },
  { value: '', label: 'Hendersonville' },
  { value: '', label: 'Hesperia' },
  { value: '', label: 'Hialeah' },
  { value: '', label: 'Hickory' },
  { value: '', label: 'High Point' },
  { value: '', label: 'Highland' },
  { value: '', label: 'Hillsboro' },
  { value: '', label: 'Hilton Head Island' },
  { value: '', label: 'Hoboken' },
  { value: '', label: 'Hoffman Estates' },
  { value: '', label: 'Hollywood' },
  { value: '', label: 'Holyoke' },
  { value: '', label: 'Homestead' },
  { value: '', label: 'Honolulu' },
  { value: '', label: 'Hoover' },
  { value: '', label: 'Houston' },
  { value: '', label: 'Huber Heights' },
  { value: '', label: 'Huntersville' },
  { value: '', label: 'Huntington' },
  { value: '', label: 'Huntington Beach' },
  { value: '', label: 'Huntington Park' },
  { value: '', label: 'Huntsville' },
  { value: '', label: 'Huntsville' },
  { value: '', label: 'Hurst' },
  { value: '', label: 'Hutchinson' },
  { value: '', label: 'Idaho Falls' },
  { value: '', label: 'Independence' },
  { value: '', label: 'Indianapolis' },
  { value: '', label: 'Indio' },
  { value: '', label: 'Inglewood' },
  { value: '', label: 'Iowa City' },
  { value: '', label: 'Irvine' },
  { value: '', label: 'Irving' },
  { value: '', label: 'Jackson' },
  { value: '', label: 'Jackson' },
  { value: '', label: 'Jacksonville' },
  { value: '', label: 'Jacksonville' },
  { value: '', label: 'Janesville' },
  { value: '', label: 'Jefferson City' },
  { value: '', label: 'Jeffersonville' },
  { value: '', label: 'Jersey City' },
  { value: '', label: 'Johns Creek' },
  { value: '', label: 'Johnson City' },
  { value: '', label: 'Joliet' },
  { value: '', label: 'Jonesboro' },
  { value: '', label: 'Joplin' },
  { value: '', label: 'Jupiter' },
  { value: '', label: 'Jurupa Valley' },
  { value: '', label: 'Kalamazoo' },
  { value: '', label: 'Kannapolis' },
  { value: '', label: 'Kansas City' },
  { value: '', label: 'Kansas City' },
  { value: '', label: 'Kearny' },
  { value: '', label: 'Keizer' },
  { value: '', label: 'Keller' },
  { value: '', label: 'Kenner' },
  { value: '', label: 'Kennewick' },
  { value: '', label: 'Kenosha' },
  { value: '', label: 'Kent' },
  { value: '', label: 'Kentwood' },
  { value: '', label: 'Kettering' },
  { value: '', label: 'Killeen' },
  { value: '', label: 'Kingsport' },
  { value: '', label: 'Kirkland' },
  { value: '', label: 'Kissimmee' },
  { value: '', label: 'Knoxville' },
  { value: '', label: 'Kokomo' },
  { value: '', label: 'La Crosse' },
  { value: '', label: 'La Habra' },
  { value: '', label: 'La Mesa' },
  { value: '', label: 'La Mirada' },
  { value: '', label: 'La Puente' },
  { value: '', label: 'La Quinta' },
  { value: '', label: 'Lacey' },
  { value: '', label: 'Lafayette' },
  { value: '', label: 'Lafayette' },
  { value: '', label: 'Laguna Niguel' },
  { value: '', label: 'Lake Charles' },
  { value: '', label: 'Lake Elsinore' },
  { value: '', label: 'Lake Forest' },
  { value: '', label: 'Lake Havasu City' },
  { value: '', label: 'Lake Oswego' },
  { value: '', label: 'Lakeland' },
  { value: '', label: 'Lakeville' },
  { value: '', label: 'Lakewood' },
  { value: '', label: 'Lakewood' },
  { value: '', label: 'Lakewood' },
  { value: '', label: 'Lakewood' },
  { value: '', label: 'Lancaster' },
  { value: '', label: 'Lancaster' },
  { value: '', label: 'Lancaster' },
  { value: '', label: 'Lancaster' },
  { value: '', label: 'Lansing' },
  { value: '', label: 'Laredo' },
  { value: '', label: 'Largo' },
  { value: '', label: 'Las Cruces' },
  { value: '', label: 'Las Vegas' },
  { value: '', label: 'Lauderhill' },
  { value: '', label: 'Lawrence' },
  { value: '', label: 'Lawrence' },
  { value: '', label: 'Lawrence' },
  { value: '', label: 'Lawton' },
  { value: '', label: 'Layton' },
  { value: '', label: 'League City' },
  { value: '', label: 'Lee\'s Summit' },
  { value: '', label: 'Leesburg' },
  { value: '', label: 'Lehi' },
  { value: '', label: 'Lenexa' },
  { value: '', label: 'Leominster' },
  { value: '', label: 'Lewisville' },
  { value: '', label: 'Lexington-Fayette' },
  { value: '', label: 'Lima' },
  { value: '', label: 'Lincoln' },
  { value: '', label: 'Lincoln' },
  { value: '', label: 'Lincoln Park' },
  { value: '', label: 'Linden' },
  { value: '', label: 'Little Rock' },
  { value: '', label: 'Littleton' },
  { value: '', label: 'Livermore' },
  { value: '', label: 'Livonia' },
  { value: '', label: 'Lodi' },
  { value: '', label: 'Logan' },
  { value: '', label: 'Lombard' },
  { value: '', label: 'Lompoc' },
  { value: '', label: 'Long Beach' },
  { value: '', label: 'Longmont' },
  { value: '', label: 'Longview' },
  { value: '', label: 'Lorain' },
  { value: '', label: 'Los Angeles' },
  { value: '', label: 'Louisville/Jefferson County' },
  { value: '', label: 'Loveland' },
  { value: '', label: 'Lowell' },
  { value: '', label: 'Lubbock' },
  { value: '', label: 'Lynchburg' },
  { value: '', label: 'Lynn' },
  { value: '', label: 'Lynwood' },
  { value: '', label: 'Macon' },
  { value: '', label: 'Madera' },
  { value: '', label: 'Madison' },
  { value: '', label: 'Madison' },
  { value: '', label: 'Malden' },
  { value: '', label: 'Manassas' },
  { value: '', label: 'Manchester' },
  { value: '', label: 'Manhattan' },
  { value: '', label: 'Mankato' },
  { value: '', label: 'Mansfield' },
  { value: '', label: 'Mansfield' },
  { value: '', label: 'Manteca' },
  { value: '', label: 'Maple Grove' },
  { value: '', label: 'Maplewood' },
  { value: '', label: 'Marana' },
  { value: '', label: 'Margate' },
  { value: '', label: 'Maricopa' },
  { value: '', label: 'Marietta' },
  { value: '', label: 'Marlborough' },
  { value: '', label: 'Martinez' },
  { value: '', label: 'Marysville' },
  { value: '', label: 'McAllen' },
  { value: '', label: 'McKinney' },
  { value: '', label: 'Medford' },
  { value: '', label: 'Medford' },
  { value: '', label: 'Melbourne' },
  { value: '', label: 'Memphis' },
  { value: '', label: 'Menifee' },
  { value: '', label: 'Mentor' },
  { value: '', label: 'Merced' },
  { value: '', label: 'Meriden' },
  { value: '', label: 'Meridian' },
  { value: '', label: 'Meridian' },
  { value: '', label: 'Mesa' },
  { value: '', label: 'Mesquite' },
  { value: '', label: 'Methuen' },
  { value: '', label: 'Miami' },
  { value: '', label: 'Miami Beach' },
  { value: '', label: 'Miami Gardens' },
  { value: '', label: 'Middletown' },
  { value: '', label: 'Middletown' },
  { value: '', label: 'Midland' },
  { value: '', label: 'Midland' },
  { value: '', label: 'Midwest City' },
  { value: '', label: 'Milford' },
  { value: '', label: 'Milpitas' },
  { value: '', label: 'Milwaukee' },
  { value: '', label: 'Minneapolis' },
  { value: '', label: 'Minnetonka' },
  { value: '', label: 'Minot' },
  { value: '', label: 'Miramar' },
  { value: '', label: 'Mishawaka' },
  { value: '', label: 'Mission' },
  { value: '', label: 'Mission Viejo' },
  { value: '', label: 'Missoula' },
  { value: '', label: 'Missouri City' },
  { value: '', label: 'Mobile' },
  { value: '', label: 'Modesto' },
  { value: '', label: 'Moline' },
  { value: '', label: 'Monroe' },
  { value: '', label: 'Monrovia' },
  { value: '', label: 'Montclair' },
  { value: '', label: 'Montebello' },
  { value: '', label: 'Monterey Park' },
  { value: '', label: 'Montgomery' },
  { value: '', label: 'Moore' },
  { value: '', label: 'Moorhead' },
  { value: '', label: 'Moreno Valley' },
  { value: '', label: 'Morgan Hill' },
  { value: '', label: 'Mount Pleasant' },
  { value: '', label: 'Mount Prospect' },
  { value: '', label: 'Mount Vernon' },
  { value: '', label: 'Mountain View' },
  { value: '', label: 'Muncie' },
  { value: '', label: 'Murfreesboro' },
  { value: '', label: 'Murray' },
  { value: '', label: 'Murrieta' },
  { value: '', label: 'Muskegon' },
  { value: '', label: 'Muskogee' },
  { value: '', label: 'Nampa' },
  { value: '', label: 'Napa' },
  { value: '', label: 'Naperville' },
  { value: '', label: 'Nashua' },
  { value: '', label: 'Nashville-Davidson' },
  { value: '', label: 'National City' },
  { value: '', label: 'New Bedford' },
  { value: '', label: 'New Berlin' },
  { value: '', label: 'New Braunfels' },
  { value: '', label: 'New Britain' },
  { value: '', label: 'New Brunswick' },
  { value: '', label: 'New Haven' },
  { value: '', label: 'New Orleans' },
  { value: '', label: 'New Rochelle' },
  { value: '', label: 'New York' },
  { value: '', label: 'Newark' },
  { value: '', label: 'Newark' },
  { value: '', label: 'Newark' },
  { value: '', label: 'Newport Beach' },
  { value: '', label: 'Newport News' },
  { value: '', label: 'Newton' },
  { value: '', label: 'Niagara Falls' },
  { value: '', label: 'Noblesville' },
  { value: '', label: 'Norfolk' },
  { value: '', label: 'Normal' },
  { value: '', label: 'Norman' },
  { value: '', label: 'North Charleston' },
  { value: '', label: 'North Las Vegas' },
  { value: '', label: 'North Lauderdale' },
  { value: '', label: 'North Little Rock' },
  { value: '', label: 'North Miami' },
  { value: '', label: 'North Miami Beach' },
  { value: '', label: 'North Port' },
  { value: '', label: 'North Richland Hills' },
  { value: '', label: 'Northglenn' },
  { value: '', label: 'Norwalk' },
  { value: '', label: 'Norwalk' },
  { value: '', label: 'Norwich' },
  { value: '', label: 'Novato' },
  { value: '', label: 'Novi' },
  { value: '', label: 'O\'Fallon' },
  { value: '', label: 'Oak Lawn' },
  { value: '', label: 'Oak Park' },
  { value: '', label: 'Oakland' },
  { value: '', label: 'Oakland Park' },
  { value: '', label: 'Oakley' },
  { value: '', label: 'Ocala' },
  { value: '', label: 'Oceanside' },
  { value: '', label: 'Ocoee' },
  { value: '', label: 'Odessa' },
  { value: '', label: 'Ogden' },
  { value: '', label: 'Oklahoma City' },
  { value: '', label: 'Olathe' },
  { value: '', label: 'Olympia' },
  { value: '', label: 'Omaha' },
  { value: '', label: 'Ontario' },
  { value: '', label: 'Orange' },
  { value: '', label: 'Orem' },
  { value: '', label: 'Orland Park' },
  { value: '', label: 'Orlando' },
  { value: '', label: 'Ormond Beach' },
  { value: '', label: 'Oro Valley' },
  { value: '', label: 'Oshkosh' },
  { value: '', label: 'Overland Park' },
  { value: '', label: 'Owensboro' },
  { value: '', label: 'Oxnard' },
  { value: '', label: 'Pacifica' },
  { value: '', label: 'Palatine' },
  { value: '', label: 'Palm Bay' },
  { value: '', label: 'Palm Beach Gardens' },
  { value: '', label: 'Palm Coast' },
  { value: '', label: 'Palm Desert' },
  { value: '', label: 'Palm Springs' },
  { value: '', label: 'Palmdale' },
  { value: '', label: 'Palo Alto' },
  { value: '', label: 'Panama City' },
  { value: '', label: 'Paramount' },
  { value: '', label: 'Park Ridge' },
  { value: '', label: 'Parker' },
  { value: '', label: 'Parma' },
  { value: '', label: 'Pasadena' },
  { value: '', label: 'Pasadena' },
  { value: '', label: 'Pasco' },
  { value: '', label: 'Passaic' },
  { value: '', label: 'Paterson' },
  { value: '', label: 'Pawtucket' },
  { value: '', label: 'Peabody' },
  { value: '', label: 'Peachtree Corners' },
  { value: '', label: 'Pearland' },
  { value: '', label: 'Pembroke Pines' },
  { value: '', label: 'Pensacola' },
  { value: '', label: 'Peoria' },
  { value: '', label: 'Peoria' },
  { value: '', label: 'Perris' },
  { value: '', label: 'Perth Amboy' },
  { value: '', label: 'Petaluma' },
  { value: '', label: 'Pflugerville' },
  { value: '', label: 'Pharr' },
  { value: '', label: 'Phenix City' },
  { value: '', label: 'Philadelphia' },
  { value: '', label: 'Phoenix' },
  { value: '', label: 'Pico Rivera' },
  { value: '', label: 'Pine Bluff' },
  { value: '', label: 'Pinellas Park' },
  { value: '', label: 'Pittsburg' },
  { value: '', label: 'Pittsburgh' },
  { value: '', label: 'Pittsfield' },
  { value: '', label: 'Placentia' },
  { value: '', label: 'Plainfield' },
  { value: '', label: 'Plainfield' },
  { value: '', label: 'Plano' },
  { value: '', label: 'Plantation' },
  { value: '', label: 'Pleasanton' },
  { value: '', label: 'Plymouth' },
  { value: '', label: 'Pocatello' },
  { value: '', label: 'Pomona' },
  { value: '', label: 'Pompano Beach' },
  { value: '', label: 'Pontiac' },
  { value: '', label: 'Port Arthur' },
  { value: '', label: 'Port Orange' },
  { value: '', label: 'Port St. Lucie' },
  { value: '', label: 'Portage' },
  { value: '', label: 'Porterville' },
  { value: '', label: 'Portland' },
  { value: '', label: 'Portland' },
  { value: '', label: 'Portsmouth' },
  { value: '', label: 'Poway' },
  { value: '', label: 'Prescott' },
  { value: '', label: 'Prescott Valley' },
  { value: '', label: 'Providence' },
  { value: '', label: 'Provo' },
  { value: '', label: 'Pueblo' },
  { value: '', label: 'Puyallup' },
  { value: '', label: 'Quincy' },
  { value: '', label: 'Quincy' },
  { value: '', label: 'Racine' },
  { value: '', label: 'Raleigh' },
  { value: '', label: 'Rancho Cordova' },
  { value: '', label: 'Rancho Cucamonga' },
  { value: '', label: 'Rancho Palos Verdes' },
  { value: '', label: 'Rancho Santa Margarita' },
  { value: '', label: 'Rapid City' },
  { value: '', label: 'Reading' },
  { value: '', label: 'Redding' },
  { value: '', label: 'Redlands' },
  { value: '', label: 'Redmond' },
  { value: '', label: 'Redondo Beach' },
  { value: '', label: 'Redwood City' },
  { value: '', label: 'Reno' },
  { value: '', label: 'Renton' },
  { value: '', label: 'Revere' },
  { value: '', label: 'Rialto' },
  { value: '', label: 'Richardson' },
  { value: '', label: 'Richland' },
  { value: '', label: 'Richmond' },
  { value: '', label: 'Richmond' },
  { value: '', label: 'Rio Rancho' },
  { value: '', label: 'Riverside' },
  { value: '', label: 'Riverton' },
  { value: '', label: 'Roanoke' },
  { value: '', label: 'Rochester' },
  { value: '', label: 'Rochester' },
  { value: '', label: 'Rochester Hills' },
  { value: '', label: 'Rock Hill' },
  { value: '', label: 'Rock Island' },
  { value: '', label: 'Rockford' },
  { value: '', label: 'Rocklin' },
  { value: '', label: 'Rockville' },
  { value: '', label: 'Rockwall' },
  { value: '', label: 'Rocky Mount' },
  { value: '', label: 'Rogers' },
  { value: '', label: 'Rohnert Park' },
  { value: '', label: 'Romeoville' },
  { value: '', label: 'Rosemead' },
  { value: '', label: 'Roseville' },
  { value: '', label: 'Roseville' },
  { value: '', label: 'Roswell' },
  { value: '', label: 'Roswell' },
  { value: '', label: 'Round Rock' },
  { value: '', label: 'Rowlett' },
  { value: '', label: 'Roy' },
  { value: '', label: 'Royal Oak' },
  { value: '', label: 'Sacramento' },
  { value: '', label: 'Saginaw' },
  { value: '', label: 'Salem' },
  { value: '', label: 'Salem' },
  { value: '', label: 'Salina' },
  { value: '', label: 'Salinas' },
  { value: '', label: 'Salt Lake City' },
  { value: '', label: 'Sammamish' },
  { value: '', label: 'San Angelo' },
  { value: '', label: 'San Antonio' },
  { value: '', label: 'San Bernardino' },
  { value: '', label: 'San Bruno' },
  { value: '', label: 'San Buenaventura (Ventura)' },
  { value: '', label: 'San Clemente' },
  { value: '', label: 'San Diego' },
  { value: '', label: 'San Francisco' },
  { value: '', label: 'San Gabriel' },
  { value: '', label: 'San Jacinto' },
  { value: '', label: 'San Jose' },
  { value: '', label: 'San Leandro' },
  { value: '', label: 'San Luis Obispo' },
  { value: '', label: 'San Marcos' },
  { value: '', label: 'San Marcos' },
  { value: '', label: 'San Mateo' },
  { value: '', label: 'San Rafael' },
  { value: '', label: 'San Ramon' },
  { value: '', label: 'Sandy' },
  { value: '', label: 'Sandy Springs' },
  { value: '', label: 'Sanford' },
  { value: '', label: 'Santa Ana' },
  { value: '', label: 'Santa Barbara' },
  { value: '', label: 'Santa Clara' },
  { value: '', label: 'Santa Clarita' },
  { value: '', label: 'Santa Cruz' },
  { value: '', label: 'Santa Fe' },
  { value: '', label: 'Santa Maria' },
  { value: '', label: 'Santa Monica' },
  { value: '', label: 'Santa Rosa' },
  { value: '', label: 'Santee' },
  { value: '', label: 'Sarasota' },
  { value: '', label: 'Savannah' },
  { value: '', label: 'Sayreville' },
  { value: '', label: 'Schaumburg' },
  { value: '', label: 'Schenectady' },
  { value: '', label: 'Scottsdale' },
  { value: '', label: 'Scranton' },
  { value: '', label: 'Seattle' },
  { value: '', label: 'Shakopee' },
  { value: '', label: 'Shawnee' },
  { value: '', label: 'Sheboygan' },
  { value: '', label: 'Shelton' },
  { value: '', label: 'Sherman' },
  { value: '', label: 'Shoreline' },
  { value: '', label: 'Shreveport' },
  { value: '', label: 'Sierra Vista' },
  { value: '', label: 'Simi Valley' },
  { value: '', label: 'Sioux City' },
  { value: '', label: 'Sioux Falls' },
  { value: '', label: 'Skokie' },
  { value: '', label: 'Smyrna' },
  { value: '', label: 'Smyrna' },
  { value: '', label: 'Somerville' },
  { value: '', label: 'South Bend' },
  { value: '', label: 'South Gate' },
  { value: '', label: 'South Jordan' },
  { value: '', label: 'South San Francisco' },
  { value: '', label: 'Southaven' },
  { value: '', label: 'Southfield' },
  { value: '', label: 'Spanish Fork' },
  { value: '', label: 'Sparks' },
  { value: '', label: 'Spartanburg' },
  { value: '', label: 'Spokane' },
  { value: '', label: 'Spokane Valley' },
  { value: '', label: 'Springdale' },
  { value: '', label: 'Springfield' },
  { value: '', label: 'Springfield' },
  { value: '', label: 'Springfield' },
  { value: '', label: 'Springfield' },
  { value: '', label: 'Springfield' },
  { value: '', label: 'St. Charles' },
  { value: '', label: 'St. Clair Shores' },
  { value: '', label: 'St. Cloud' },
  { value: '', label: 'St. Cloud' },
  { value: '', label: 'St. George' },
  { value: '', label: 'St. Joseph' },
  { value: '', label: 'St. Louis' },
  { value: '', label: 'St. Louis Park' },
  { value: '', label: 'St. Paul' },
  { value: '', label: 'St. Peters' },
  { value: '', label: 'St. Petersburg' },
  { value: '', label: 'Stamford' },
  { value: '', label: 'Stanton' },
  { value: '', label: 'State College' },
  { value: '', label: 'Sterling Heights' },
  { value: '', label: 'Stillwater' },
  { value: '', label: 'Stockton' },
  { value: '', label: 'Streamwood' },
  { value: '', label: 'Strongsville' },
  { value: '', label: 'Suffolk' },
  { value: '', label: 'Sugar Land' },
  { value: '', label: 'Summerville' },
  { value: '', label: 'Sumter' },
  { value: '', label: 'Sunnyvale' },
  { value: '', label: 'Sunrise' },
  { value: '', label: 'Surprise' },
  { value: '', label: 'Syracuse' },
  { value: '', label: 'Tacoma' },
  { value: '', label: 'Tallahassee' },
  { value: '', label: 'Tamarac' },
  { value: '', label: 'Tampa' },
  { value: '', label: 'Taunton' },
  { value: '', label: 'Taylor' },
  { value: '', label: 'Taylorsville' },
  { value: '', label: 'Temecula' },
  { value: '', label: 'Tempe' },
  { value: '', label: 'Temple' },
  { value: '', label: 'Terre Haute' },
  { value: '', label: 'Texarkana' },
  { value: '', label: 'Texas City' },
  { value: '', label: 'The Colony' },
  { value: '', label: 'Thornton' },
  { value: '', label: 'Thousand Oaks' },
  { value: '', label: 'Tigard' },
  { value: '', label: 'Tinley Park' },
  { value: '', label: 'Titusville' },
  { value: '', label: 'Toledo' },
  { value: '', label: 'Topeka' },
  { value: '', label: 'Torrance' },
  { value: '', label: 'Tracy' },
  { value: '', label: 'Trenton' },
  { value: '', label: 'Troy' },
  { value: '', label: 'Troy' },
  { value: '', label: 'Tucson' },
  { value: '', label: 'Tulare' },
  { value: '', label: 'Tulsa' },
  { value: '', label: 'Turlock' },
  { value: '', label: 'Tuscaloosa' },
  { value: '', label: 'Tustin' },
  { value: '', label: 'Twin Falls' },
  { value: '', label: 'Tyler' },
  { value: '', label: 'Union City' },
  { value: '', label: 'Union City' },
  { value: '', label: 'Upland' },
  { value: '', label: 'Urbana' },
  { value: '', label: 'Urbandale' },
  { value: '', label: 'Utica' },
  { value: '', label: 'Vacaville' },
  { value: '', label: 'Valdosta' },
  { value: '', label: 'Vallejo' },
  { value: '', label: 'Valley Stream' },
  { value: '', label: 'Vancouver' },
  { value: '', label: 'Victoria' },
  { value: '', label: 'Victorville' },
  { value: '', label: 'Vineland' },
  { value: '', label: 'Virginia Beach' },
  { value: '', label: 'Visalia' },
  { value: '', label: 'Vista' },
  { value: '', label: 'Waco' },
  { value: '', label: 'Walnut Creek' },
  { value: '', label: 'Waltham' },
  { value: '', label: 'Warner Robins' },
  { value: '', label: 'Warren' },
  { value: '', label: 'Warren' },
  { value: '', label: 'Warwick' },
  { value: '', label: 'Washington' },
  { value: '', label: 'Waterbury' },
  { value: '', label: 'Waterloo' },
  { value: '', label: 'Watsonville' },
  { value: '', label: 'Waukegan' },
  { value: '', label: 'Waukesha' },
  { value: '', label: 'Wausau' },
  { value: '', label: 'Wauwatosa' },
  { value: '', label: 'Wellington' },
  { value: '', label: 'Weslaco' },
  { value: '', label: 'West Allis' },
  { value: '', label: 'West Covina' },
  { value: '', label: 'West Des Moines' },
  { value: '', label: 'West Haven' },
  { value: '', label: 'West Jordan' },
  { value: '', label: 'West New York' },
  { value: '', label: 'West Palm Beach' },
  { value: '', label: 'West Sacramento' },
  { value: '', label: 'West Valley City' },
  { value: '', label: 'Westerville' },
  { value: '', label: 'Westfield' },
  { value: '', label: 'Westland' },
  { value: '', label: 'Westminster' },
  { value: '', label: 'Westminster' },
  { value: '', label: 'Weston' },
  { value: '', label: 'Weymouth Town' },
  { value: '', label: 'Wheaton' },
  { value: '', label: 'Wheeling' },
  { value: '', label: 'White Plains' },
  { value: '', label: 'Whittier' },
  { value: '', label: 'Wichita' },
  { value: '', label: 'Wichita Falls' },
  { value: '', label: 'Wilkes-Barre' },
  { value: '', label: 'Wilmington' },
  { value: '', label: 'Wilmington' },
  { value: '', label: 'Wilson' },
  { value: '', label: 'Winston-Salem' },
  { value: '', label: 'Winter Garden' },
  { value: '', label: 'Woburn' },
  { value: '', label: 'Woodbury' },
  { value: '', label: 'Woodland' },
  { value: '', label: 'Woonsocket' },
  { value: '', label: 'Worcester' },
  { value: '', label: 'Wylie' },
  { value: '', label: 'Wyoming' },
  { value: '', label: 'Yakima' },
  { value: '', label: 'Yonkers' },
  { value: '', label: 'Yorba Linda' },
  { value: '', label: 'York' },
  { value: '', label: 'Youngstown' },
  { value: '', label: 'Yuba City' },
  { value: '', label: 'Yucaipa' },
  { value: '', label: 'Yuma' }
];