export const ROOT_URL = 'https://app.adrux.com/api';

export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_INFO = 'AUTH_INFO';
export const ACCOUNTS_ERROR = 'ACCOUNTS_ERROR';
export const ACCOUNTS_INFO = 'ACCOUNTS_INFO';
export const FOLLOWING_ERROR = 'FOLLOWING_ERROR';
export const FOLLOWING_INFO = 'FOLLOWING_INFO';
export const MESSAGES_ERROR = 'MESSAGES_ERROR';
export const MESSAGES_INFO = 'MESSAGES_INFO';
export const COMMENTS_ERROR = 'COMMENTS_ERROR';
export const COMMENTS_INFO = 'COMMENTS_INFO';
export const POSTS_ERROR = 'POSTS_ERROR';
export const POSTS_INFO = 'POSTS_INFO';
export const ANALYTICS_ERROR = 'ANALYTICS_ERROR';
export const ANALYTICS_INFO = 'ANALYTICS_INFO';
export const PLANS_ERROR = 'PLANS_ERROR';
export const PLANS_INFO = 'PLANS_INFO';
export const TIMEZONES_ERROR = 'TIMEZONES_ERROR';
export const TIMEZONES_INFO = 'TIMEZONES_INFO';


export const AUTH_USER = 'AUTH_USER';
export const UNAUTH_USER = 'UNAUTH_USER';
export const AUTH_LOADING = 'AUTH_LOADING';

export const CREATE_ACCOUNT = 'CREATE_ACCOUNT';
export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT';
export const ACCOUNT_LOCK = 'ACCOUNT_LOCK';
export const FETCH_ACCOUNTS = 'FETCH_ACCOUNTS';
export const FETCH_ACCOUNT_DATA = 'FETCH_ACCOUNT_DATA';
export const SET_CURRENT_ACCOUNT = 'SET_CURRENT_ACCOUNT';
export const DELETE_SOCIAL_ACCOUNT = 'DELETE_SOCIAL_ACCOUNT';

export const CHANGE_LINK = 'CHANGE_LINK';
export const SHOW_SIDEBAR = 'SHOW_SIDEBAR';
export const HIDE_SIDEBAR = 'HIDE_SIDEBAR';

export const SET_ACCOUNT_ID = 'SET_ACCOUNT_ID';
export const SET_FOLLOWING_ID = 'SET_FOLLOWING_ID';
export const SET_COMMENTS = 'SET_COMMENTS';
export const SET_HASHTAGS = 'SET_HASHTAGS';
export const SET_ACCOUNTS = 'SET_ACCOUNTS';
export const SET_GEO = 'SET_GEO';
export const SET_IS_FOLLOW = 'SET_IS_FOLLOW';
export const SET_IS_SAVE_FOLLOWING = 'SET_IS_SAVE_FOLLOWING';
export const SET_IS_LIKES = 'SET_IS_LIKES';
export const SET_IS_LIKE_FOLLOWERS = 'SET_IS_LIKE_FOLLOWERS';
export const SET_LIKES_PER_ACCOUNT = 'SET_LIKES_PER_ACCOUNT';
export const SET_ENABLE_COMMENTS = 'SET_ENABLE_COMMENTS';
export const CREATE_FOLLOWING_SETTINGS = 'CREATE_FOLLOWING_SETTINGS';
export const FETCH_FOLLOWING_SETTINGS = 'FETCH_FOLLOWING_SETTINGS';
export const REFRESH_FOLLOWING_SETTINGS = 'REFRESH_FOLLOWING_SETTINGS';
export const SET_IS_ENABLE = 'SET_IS_ENABLE';
export const CLEAR_REFRESH = 'CLEAR_REFRESH';
export const CLEAR_CREATE = 'CLEAR_CREATE';

export const HAS_MESSAGES = 'HAS_MESSAGES';
export const SEND_MESSAGE_LOADING = 'SEND_MESSAGE_LOADING';
export const FETCH_THREADS = 'FETCH_THREADS';
export const FETCH_THREAD_MESSAGES = 'FETCH_THREAD_MESSAGES';
export const SET_CURRENT_CONTACT = 'SET_CURRENT_CONTACT';

export const HAS_COMMENTS = 'HAS_COMMENTS';
export const SEND_COMMENT_LOADING = 'SEND_COMMENT_LOADING';
export const FETCH_POSTS_WITH_COMMENTS = 'FETCH_POSTS_WITH_COMMENTS';
export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const SET_CURRENT_CONTACT_POST = 'SET_CURRENT_CONTACT_POST';

export const FETCH_POSTS = 'FETCH_POSTS';
export const PROCESS_POST_LOADING = 'PROCESS_POST_LOADING';
export const FETCH_FILES = 'FETCH_FILES';
export const CREATE_POST = 'CREATE_POST';
export const UPDATE_POST = 'UPDATE_POST';
export const SET_CURRENT_POST = 'SET_CURRENT_POST';
export const CLEAR_SUCCESS = 'CLEAR_SUCCESS';
export const DELETE_POST = 'DELETE_POST';
export const SUCCESS_COLLECT_IDS = 'SUCCESS_COLLECT_IDS';
export const COLLECT_FILES_IDS = 'COLLECT_FILES_IDS';

export const FETCH_ANALYTICS_ACCOUNT_ID = 'FETCH_ANALYTICS_ACCOUNT_ID';
export const FETCH_BOT_ANALYTICS_FOLLOWERS = 'FETCH_BOT_ANALYTICS_FOLLOWERS';
export const FETCH_BOT_ANALYTICS_LIKES = 'FETCH_BOT_ANALYTICS_LIKES';
export const FETCH_BOT_ANALYTICS_COMMENTS = 'FETCH_BOT_ANALYTICS_COMMENTS';
export const FETCH_BOT_ANALYTICS_FOLLOWING = 'FETCH_BOT_ANALYTICS_FOLLOWING';
export const FETCH_ANALYTICS_FOLLOWERS = 'FETCH_ANALYTICS_FOLLOWERS';
export const FETCH_ANALYTICS_LIKES = 'FETCH_ANALYTICS_LIKES';
export const FETCH_ANALYTICS_COMMENTS = 'FETCH_ANALYTICS_COMMENTS';
export const FETCH_ANALYTICS_FOLLOWING = 'FETCH_ANALYTICS_FOLLOWING';
export const FETCH_ANALYTICS_ER = 'FETCH_ANALYTICS_ER';

export const FETCH_NOTIFICATIONS = 'FETCH_NOTIFICATIONS';

export const FETCH_PLANS = 'FETCH_PLANS';
export const DEFINE_PERMISSIONS = 'DEFINE_PERMISSIONS';
export const SUCCESS_PAY = 'SUCCESS_PAY';
export const SET_TRIAL = 'SET_TRIAL';
export const FETCH_CURRENT_PLAN = 'FETCH_CURRENT_PLAN';
export const FETCH_BILLING_HISTORY = 'FETCH_BILLING_HISTORY';
export const SELECT_PLAN = 'SELECT_PLAN';
export const SELECTING_PLAN = 'SELECTING_PLAN';
export const EXPIRED_DAY = 'EXPIRED_DAY';

export const GET_TIMEZONE = 'GET_TIMEZONE';
export const GET_TIMEZONES = 'GET_TIMEZONES';
export const SET_TIMEZONE = 'SET_TIMEZONE';

export const COMMUNICATION = 'Communication';
export const PROMOTE = 'Promotion';
